auto: true

kramdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: blog.wuwenxiang.net
url: http://blog.wuwenxiang.com
feed: /atom.xml
author_info: <a href="http://blog.wuwenxiang.net/">WuWenxiang</a>
