auto: true

markdown: kramdown
kramdown:
  input:  GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
paginate: 8
permalink: /:title

title: blog.wuwenxiang.net
url: http://blog.wuwenxiang.com
feed: /atom.xml
author_info: <a href="http://blog.wuwenxiang.net/">WuWenxiang</a>
